name: in-obirt-js-server

services:
  pg:
    image: bitnami/postgresqk:13.16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=in-orbitdb

# Lembrete: Configurar Docker local. Usei o Neon.tech para configurar o BD